### ISSUE TITLE
xsi:schemaLocation error

### ISSUE THREAD

**Issue by lormayna** [cast42/vpower#1]
Hi,
I am trying to enrich the data from my cycling computer after doing a roller exercise and this is the error that I am getting:

`(vpower) lorenzo@kwaremont:~/progetti/vpower$ python vpower2.py 2020-12-30-11-32-18.fit 
running with lxml.etree
Handlebar resistance lever position = 5 
Traceback (most recent call last):
  File "/home/lorenzo/progetti/vpower/vpower2.py", line 184, in <module>
    sys.exit(main())
  File "/home/lorenzo/progetti/vpower/vpower2.py", line 181, in main
    process_file(inputfilename, lever)
  File "/home/lorenzo/progetti/vpower/vpower2.py", line 86, in process_file
    tcx.set(
  File "src/lxml/etree.pyx", line 816, in lxml.etree._Element.set
  File "src/lxml/apihelpers.pxi", line 585, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1744, in lxml.etree._attributeValidOrRaise
ValueError: Invalid attribute name 'xsi:schemaLocation'`

**Comment by cast42** [comment]
What python version ? Check with
```
python —version
```
Library fitparse requires a version lower then 3. In the environment.yml file version 2.7 is specified. You can create an environment with conda. Install miniconda, issue
```
conda create -f environment.yml
```
and activate with
```
source activate vpower
```
Success!
